---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: som
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "somg0703/minispe"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name minispe somg0703/minispe